name: picbox
description: An online search image, download the collection of APP .

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter

    cupertino_icons: ^0.1.2
    dio: ^1.0.13
    flutter_easyrefresh: ^1.2.5
    #图像浏览
    #transparent_image: ^0.1.0
    photo_view: ^0.2.0
    #数据持久化
    sqflite: any
    crypto: ^2.0.6
    image_picker: ^0.5.0+3
    xml2json: ^3.0.3
    path_provider: ^0.4.1
    #视频播放
    chewie: ^0.9.6

dev_dependencies:
    flutter_test:
      sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app.db
    - assets/images/
    - locale/