name: picbox
description: An online search image, download the collection of APP .

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
      sdk: flutter

    cupertino_icons: ^0.1.2
    dio: ^1.0.13
    flutter_easyrefresh: ^1.2.5
    #图像浏览
    transparent_image: ^0.1.0
    photo_view: ^0.1.2
    #数据持久化
    shared_preferences: ^0.4.3
    sqflite: any
    # https://github.com/tekartik/synchronized.dart
    synchronized: ^1.5.3
    crypto: ^2.0.6
    image_picker: ^0.5.0+3
    flutter_gallery_assets: 0.1.8
    xml2json: ^3.0.3
    path_provider: ^0.4.1

dev_dependencies:
    flutter_test:
      sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/app.db
    - assets/images/ali_connors.png
    - assets/images/ali_connors_sml.png
    - assets/images/folder.png
    - assets/images/image.png
    - assets/images/ppt.png
    - assets/images/word.png
    - assets/images/excel.png
    - assets/images/txt.png
    - assets/images/file.png
    - assets/images/zip.png
    - assets/images/mp3.png
    - assets/images/video.png
    - assets/images/psd.png
    - assets/images/unknown.png
    - assets/images/image.jpg